BEGIN;

DROP TABLE IF EXISTS webauthn CASCADE;
DROP TABLE IF EXISTS thread_content CASCADE;
DROP TABLE IF EXISTS thread CASCADE;
DROP TABLE IF EXISTS starred CASCADE;
DROP TABLE IF EXISTS search_index CASCADE;
DROP TABLE IF EXISTS remember_login CASCADE;
DROP TABLE IF EXISTS login_history CASCADE;
DROP TABLE IF EXISTS links CASCADE;
DROP TABLE IF EXISTS history CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS editrequest CASCADE;
DROP TABLE IF EXISTS email_keys CASCADE;
DROP TABLE IF EXISTS cookies CASCADE;
DROP TABLE IF EXISTS acl_document CASCADE;
DROP TABLE IF EXISTS acl_namespace CASCADE;
DROP TABLE IF EXISTS "BlockHistory" CASCADE;
DROP TABLE IF EXISTS aclgroups CASCADE;
DROP TABLE IF EXISTS config CASCADE;
DROP TABLE IF EXISTS document CASCADE;
DROP TABLE IF EXISTS ip CASCADE;
DROP TABLE IF EXISTS member CASCADE;

CREATE TABLE aclgroups (
  groupid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE config (
  key TEXT NOT NULL,
  value TEXT NOT NULL
);

CREATE TABLE document (
  uuid BYTEA NOT NULL PRIMARY KEY,
  namespace TEXT NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'normal',
  backlink_updated SMALLINT NOT NULL DEFAULT 0,
  UNIQUE (namespace, title)
);

CREATE INDEX document_namespace_title_idx ON document(namespace, title);

CREATE TABLE ip (
  uuid BYTEA NOT NULL PRIMARY KEY,
  ip BYTEA UNIQUE
);

CREATE TABLE member (
  uuid BYTEA NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  password TEXT,
  email TEXT NOT NULL UNIQUE,
  last_login_ua TEXT,
  skin TEXT,
  registered INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  registered_ip BYTEA,
  totp_secret TEXT,
  perm TEXT,
  settings TEXT
);

CREATE TABLE acl_document (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid BYTEA NOT NULL,
  access TEXT NOT NULL,
  condition TEXT NOT NULL,
  action TEXT NOT NULL,
  until INTEGER NOT NULL,
  FOREIGN KEY (uuid) REFERENCES document(uuid)
);

CREATE INDEX acl_document_uuid_idx ON acl_document(uuid);

CREATE TABLE acl_namespace (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  namespace TEXT NOT NULL,
  access TEXT NOT NULL,
  condition TEXT NOT NULL,
  action TEXT NOT NULL,
  until INTEGER NOT NULL
);

CREATE TABLE "BlockHistory" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  executor_m BYTEA,
  executor_i BYTEA,
  target_ip BYTEA,
  mask INTEGER,
  target_member BYTEA,
  target_ip_uuid BYTEA,
  target_aclgroup TEXT,
  comment TEXT,
  datetime BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
  until BIGINT,
  action TEXT NOT NULL,
  granted TEXT,
  FOREIGN KEY (executor_m) REFERENCES member(uuid),
  FOREIGN KEY (target_member) REFERENCES member(uuid),
  FOREIGN KEY (target_ip_uuid) REFERENCES ip(uuid)
);

CREATE INDEX blockhistory_executor_idx ON "BlockHistory"(executor_m);
CREATE INDEX blockhistory_target_member_idx ON "BlockHistory"(target_member);
CREATE INDEX blockhistory_target_ip_uuid_idx ON "BlockHistory"(target_ip_uuid);
CREATE INDEX blockhistory_target_aclgroup_idx ON "BlockHistory"(target_aclgroup);

CREATE TABLE cookies (
  "user" BYTEA NOT NULL,
  name TEXT NOT NULL,
  value BYTEA NOT NULL UNIQUE,
  expiry INTEGER NOT NULL,
  created INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  FOREIGN KEY ("user") REFERENCES member(uuid) ON DELETE CASCADE
);

CREATE INDEX cookies_user_idx ON cookies("user");

CREATE TABLE email_keys (
  email TEXT NOT NULL PRIMARY KEY,
  ip BYTEA NOT NULL,
  key BYTEA NOT NULL,
  time INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER)
);

CREATE INDEX email_keys_key_idx ON email_keys(key);
CREATE INDEX email_keys_time_idx ON email_keys(time);

CREATE TABLE editrequest (
  urlstr TEXT NOT NULL PRIMARY KEY,
  document BYTEA NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  comment TEXT,
  content TEXT NOT NULL,
  contributor_m BYTEA,
  contributor_i BYTEA,
  baserev INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  datetime INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  lastedit INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  executor_m BYTEA,
  executor_i BYTEA,
  acceptrev INTEGER,
  reason TEXT,
  FOREIGN KEY (document) REFERENCES document(uuid),
  FOREIGN KEY (contributor_m) REFERENCES member(uuid),
  FOREIGN KEY (contributor_i) REFERENCES ip(uuid),
  FOREIGN KEY (executor_m) REFERENCES member(uuid),
  FOREIGN KEY (executor_i) REFERENCES ip(uuid)
);

CREATE INDEX editrequest_document_idx ON editrequest(document);

CREATE TABLE files (
  uuid BYTEA NOT NULL,
  hash BYTEA NOT NULL UNIQUE,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  FOREIGN KEY (uuid) REFERENCES document(uuid)
);

CREATE INDEX files_uuid_idx ON files(uuid);

CREATE TABLE history (
  uuid BYTEA NOT NULL PRIMARY KEY,
  document BYTEA NOT NULL,
  rev INTEGER NOT NULL DEFAULT 1,
  content TEXT,
  comment TEXT NOT NULL DEFAULT '',
  datetime INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  action TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  reverted_version INTEGER,
  contributor_m BYTEA,
  contributor_i BYTEA,
  edit_request_uri TEXT,
  acl_changed TEXT,
  moved_from TEXT,
  moved_to TEXT,
  status TEXT NOT NULL DEFAULT 'normal',
  hide_log_user BYTEA,
  mark_troll_user BYTEA,
  revstatus TEXT NOT NULL DEFAULT 'normal',
  FOREIGN KEY (document) REFERENCES document(uuid),
  FOREIGN KEY (contributor_i) REFERENCES ip(uuid),
  FOREIGN KEY (contributor_m) REFERENCES member(uuid),
  FOREIGN KEY (hide_log_user) REFERENCES member(uuid),
  FOREIGN KEY (mark_troll_user) REFERENCES member(uuid)
);

CREATE INDEX history_document_rev_idx ON history(document, rev);
CREATE INDEX history_datetime_idx ON history(datetime);
CREATE INDEX history_contributor_i_idx ON history(contributor_i);
CREATE INDEX history_contributor_m_idx ON history(contributor_m);

CREATE TABLE links (
  namespace TEXT NOT NULL,
  title TEXT NOT NULL,
  from_uuid BYTEA NOT NULL,
  type TEXT NOT NULL,
  UNIQUE (namespace, title, from_uuid, type),
  FOREIGN KEY (from_uuid) REFERENCES document(uuid)
);

CREATE INDEX links_from_uuid_idx ON links(from_uuid);
CREATE INDEX links_namespace_title_idx ON links(namespace, title);

CREATE TABLE login_history (
  uuid BYTEA NOT NULL,
  ip TEXT NOT NULL,
  datetime INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  FOREIGN KEY (uuid) REFERENCES member(uuid)
);

CREATE INDEX login_history_uuid_idx ON login_history(uuid);

CREATE TABLE remember_login (
  "user" BYTEA NOT NULL,
  ip BYTEA NOT NULL,
  useragent TEXT NOT NULL,
  FOREIGN KEY ("user") REFERENCES member(uuid)
);

CREATE INDEX remember_login_user_idx ON remember_login("user");

CREATE TABLE search_index (
  document BYTEA NOT NULL PRIMARY KEY,
  text TEXT NOT NULL,
  FOREIGN KEY (document) REFERENCES document(uuid)
);

CREATE TABLE starred (
  document BYTEA NOT NULL,
  "user" BYTEA NOT NULL,
  PRIMARY KEY (document, "user"),
  FOREIGN KEY (document) REFERENCES document(uuid),
  FOREIGN KEY ("user") REFERENCES member(uuid) ON DELETE CASCADE
);

CREATE INDEX starred_user_idx ON starred("user");

CREATE TABLE thread (
  urlstr TEXT NOT NULL PRIMARY KEY,
  document BYTEA NOT NULL,
  topic TEXT NOT NULL,
  status TEXT NOT NULL,
  FOREIGN KEY (document) REFERENCES document(uuid)
);

CREATE INDEX thread_document_idx ON thread(document);

CREATE TABLE thread_content (
  urlstr TEXT NOT NULL,
  no INTEGER NOT NULL,
  contributor_m BYTEA,
  contributor_i BYTEA,
  type TEXT,
  content TEXT NOT NULL,
  datetime INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  blind TEXT,
  PRIMARY KEY (urlstr, no),
  FOREIGN KEY (urlstr) REFERENCES thread(urlstr),
  FOREIGN KEY (contributor_i) REFERENCES ip(uuid),
  FOREIGN KEY (contributor_m) REFERENCES member(uuid)
);

CREATE INDEX thread_content_urlstr_idx ON thread_content(urlstr);
CREATE INDEX thread_content_contributor_i_idx ON thread_content(contributor_i);
CREATE INDEX thread_content_contributor_m_idx ON thread_content(contributor_m);

CREATE TABLE webauthn (
  uuid BYTEA NOT NULL,
  name TEXT NOT NULL,
  registered INTEGER NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW())::INTEGER),
  lastuse INTEGER,
  client_data TEXT NOT NULL,
  UNIQUE (uuid, name),
  FOREIGN KEY (uuid) REFERENCES member(uuid) ON DELETE CASCADE
);

COMMIT;
